Repository DogCatSquare/BE, pull requests merged in 2025-02, with the labels that each got.

#48 이벤트 관련, 유저정보 수정 API
  src/main/java/DC_square/spring/domain/entity/Event.java
  src/main/java/DC_square/spring/domain/entity/User.java
  src/main/java/DC_square/spring/repository/EventRepository.java
  src/main/java/DC_square/spring/service/EventService.java
  src/main/java/DC_square/spring/service/UserService.java
  src/main/java/DC_square/spring/web/controller/EmailController.java
  src/main/java/DC_square/spring/web/controller/EventController.java
  src/main/java/DC_square/spring/web/controller/UserController.java
  src/main/java/DC_square/spring/web/dto/request/EventCreateRequestDto.java
  src/main/java/DC_square/spring/web/dto/request/user/UserUpdateRequestDto.java
  src/main/java/DC_square/spring/web/dto/response/EventResponseDto.java
Labels: :sparkle:

#50 구글 지도 api 구현
  build.gradle
  src/main/java/DC_square/spring/config/GoogleMapsConfig.java
  src/main/java/DC_square/spring/config/RestTemplateConfig.java
  src/main/java/DC_square/spring/domain/entity/place/Place.java
  src/main/java/DC_square/spring/domain/entity/place/PlaceDetail.java
  src/main/java/DC_square/spring/domain/entity/place/PlaceImage.java
  src/main/java/DC_square/spring/repository/place/PlaceRepository.java
  src/main/java/DC_square/spring/service/place/GooglePlacesService.java
  src/main/java/DC_square/spring/service/place/PlaceService.java
  src/main/java/DC_square/spring/web/dto/request/place/PlaceRequestDTO.java
  src/main/java/DC_square/spring/web/dto/response/place/PlaceDetailResponseDTO.java
  src/main/java/DC_square/spring/web/dto/response/place/PlaceResponseDTO.java
  src/main/resources/application.yml
Labels: :sparkle:

#55 지도 카테고리 버그 수정
  src/main/java/DC_square/spring/service/place/PlaceService.java
  src/main/java/DC_square/spring/web/controller/RegionController.java
  src/main/java/DC_square/spring/web/controller/place/PlaceController.java
  src/main/java/DC_square/spring/web/controller/place/PlaceReviewController.java
Labels: :bug:

#61 게시판 검색기능, 특정 게시판에 있는 게시글들 조회
  src/main/java/DC_square/spring/repository/community/BoardRepository.java
  src/main/java/DC_square/spring/repository/community/PostRepository.java
  src/main/java/DC_square/spring/service/community/BoardService.java
  src/main/java/DC_square/spring/service/community/PostService.java
  src/main/java/DC_square/spring/web/controller/community/BoardController.java
  src/main/java/DC_square/spring/web/controller/community/PostController.java
Labels: :sparkle:

#62 장소 위시리스트 기능 구현
  src/main/java/DC_square/spring/domain/entity/place/PlaceWish.java
  src/main/java/DC_square/spring/repository/place/PlaceWishRepository.java
  src/main/java/DC_square/spring/service/place/PlaceService.java
  src/main/java/DC_square/spring/service/place/PlaceWishService.java
  src/main/java/DC_square/spring/web/controller/place/PlaceController.java
  src/main/java/DC_square/spring/web/controller/place/PlaceWishController.java
  src/main/java/DC_square/spring/web/dto/response/place/PlaceDetailResponseDTO.java
Labels: :sparkle:

#63 모든 게시판 조회
  src/main/java/DC_square/spring/service/community/BoardService.java
  src/main/java/DC_square/spring/web/controller/community/BoardController.java
Labels: :sparkle:

#65 장소 세부 사항 수정
  src/main/java/DC_square/spring/domain/entity/Region.java
  src/main/java/DC_square/spring/domain/entity/place/Place.java
  src/main/java/DC_square/spring/repository/place/PlaceRepository.java
  src/main/java/DC_square/spring/service/place/GooglePlacesService.java
  src/main/java/DC_square/spring/service/place/PlaceReviewService.java
  src/main/java/DC_square/spring/service/place/PlaceService.java
  src/main/java/DC_square/spring/web/controller/place/PlaceController.java
  src/main/java/DC_square/spring/web/controller/place/PlaceReviewController.java
  src/main/java/DC_square/spring/web/controller/place/PlaceWishController.java
  src/main/java/DC_square/spring/web/dto/request/place/PlaceRequestDTO.java
  src/main/java/DC_square/spring/web/dto/request/place/PlaceReviewCreateRequestDTO.java
  src/main/java/DC_square/spring/web/dto/response/place/PlaceResponseDTO.java
  src/main/java/DC_square/spring/web/dto/response/place/PlaceReviewResponseDTO.java
Labels: :bug:, :sparkle:

#67 이미지 그룹 추가로 yml 수정
  src/main/java/DC_square/spring/config/AmazonConfig.java
  src/main/java/DC_square/spring/config/S3/AmazonS3Manager.java
  src/main/resources/application.yml
Labels: init

#69 홈 화면 상단 부 기상청 단기예보 API 연동
  build.gradle
  src/main/java/DC_square/spring/config/SwaggerConfig.java
  src/main/java/DC_square/spring/constant/ImageConstants.java
  src/main/java/DC_square/spring/constant/WeatherConstants.java
  src/main/java/DC_square/spring/domain/entity/Dday.java
  src/main/java/DC_square/spring/domain/entity/User.java
  src/main/java/DC_square/spring/domain/entity/region/City.java
  src/main/java/DC_square/spring/domain/enums/WeatherStatus.java
  src/main/java/DC_square/spring/repository/region/CityRepository.java
  src/main/java/DC_square/spring/repository/region/DistrictRepository.java
  src/main/java/DC_square/spring/repository/region/ProvinceRepository.java
  src/main/java/DC_square/spring/service/RegionService.java
  src/main/java/DC_square/spring/service/UserService.java
  src/main/java/DC_square/spring/service/WeatherService.java
  src/main/java/DC_square/spring/web/controller/RegionController.java
  src/main/java/DC_square/spring/web/controller/WeatherController.java
  src/main/java/DC_square/spring/web/dto/response/UserResponseDto.java
  src/main/java/DC_square/spring/web/dto/response/WeatherResponseDto.java
  src/main/java/DC_square/spring/web/dto/response/user/UserInqueryResponseDto.java
  src/main/resources/application.yml
Labels: :sparkle:

#72 디데이 수정 api, 인증 html수정, 시간 대 아시아/서울로 변경
  src/main/java/DC_square/spring/domain/entity/Dday.java
  src/main/java/DC_square/spring/service/EmailService.java
  src/main/java/DC_square/spring/service/dday/DdayService.java
  src/main/java/DC_square/spring/web/controller/dday/DdayController.java
  src/main/java/DC_square/spring/web/dto/request/dday/DdayUpdateRequestDto.java
  src/main/java/DC_square/spring/web/dto/response/dday/DdayResponseDto.java
  src/main/resources/application.yml
Labels: :sparkle:

#73 :sparkles: : UTC 시간 문제 해결 중
  src/main/java/DC_square/spring/service/WeatherService.java
Labels: :bug:

#76 마이 리뷰 api 구현
  src/main/java/DC_square/spring/repository/WalkRepository/WalkReviewRepository.java
  src/main/java/DC_square/spring/repository/place/PlaceReviewRepository.java
  src/main/java/DC_square/spring/service/MyReviewService.java
  src/main/java/DC_square/spring/service/place/PlaceReviewService.java
  src/main/java/DC_square/spring/service/place/PlaceService.java
  src/main/java/DC_square/spring/web/controller/MyReviewController.java
  src/main/java/DC_square/spring/web/controller/place/PlaceReviewController.java
  src/main/java/DC_square/spring/web/dto/response/ReviewResponseDTO.java
  src/main/java/DC_square/spring/web/dto/response/place/PlaceDetailResponseDTO.java
  src/main/java/DC_square/spring/web/dto/response/place/PlaceResponseDTO.java
  src/main/resources/application.yml
Labels: :sparkle:

#78 페이징 처리 구현
  src/main/java/DC_square/spring/domain/entity/place/PlaceReview.java
  src/main/java/DC_square/spring/service/MyReviewService.java
  src/main/java/DC_square/spring/service/place/GooglePlacesService.java
  src/main/java/DC_square/spring/service/place/PlaceReviewService.java
  src/main/java/DC_square/spring/service/place/PlaceService.java
  src/main/java/DC_square/spring/web/controller/MyReviewController.java
  src/main/java/DC_square/spring/web/controller/place/PlaceController.java
  src/main/java/DC_square/spring/web/controller/place/PlaceReviewController.java
  src/main/java/DC_square/spring/web/dto/request/place/PlacePageRequestDTO.java
  src/main/java/DC_square/spring/web/dto/response/place/PlacePageResponseDTO.java
Labels: :sparkle:

#80 내가 작성한 게시글들 조회, 인기글 조회
  src/main/java/DC_square/spring/domain/entity/community/MyBoard.java
  src/main/java/DC_square/spring/repository/community/MyBoardRepository.java
  src/main/java/DC_square/spring/repository/community/PostRepository.java
  src/main/java/DC_square/spring/service/community/MyBoardService.java
  src/main/java/DC_square/spring/service/community/PostService.java
  src/main/java/DC_square/spring/web/controller/community/MyBoardController.java
  src/main/java/DC_square/spring/web/controller/community/PostController.java
  src/main/java/DC_square/spring/web/dto/response/community/MyBoardResponseDto.java
Labels: :sparkle:

#84 :sparkles: : 로그인/회원가입 응답추가 (city,district Id)
  src/main/java/DC_square/spring/service/UserService.java
  src/main/java/DC_square/spring/web/dto/response/UserResponseDto.java
  src/main/java/DC_square/spring/web/dto/response/user/LoginResponseDto.java
Labels: :sparkle:

#85 마이리뷰 타이틀 추가, 검색기능 버그 수정, 이용자 키워드와 기타사항 추가 기능 구현
  src/main/java/DC_square/spring/domain/entity/place/Place.java
  src/main/java/DC_square/spring/domain/entity/place/PlaceDetail.java
  src/main/java/DC_square/spring/service/MyReviewService.java
  src/main/java/DC_square/spring/service/place/GooglePlacesService.java
  src/main/java/DC_square/spring/service/place/PlaceService.java
  src/main/java/DC_square/spring/web/controller/place/PlaceController.java
  src/main/java/DC_square/spring/web/dto/request/place/PlaceCreateRequestDTO.java
  src/main/java/DC_square/spring/web/dto/request/place/PlaceUserInfoUpdateDTO.java
  src/main/java/DC_square/spring/web/dto/response/ReviewResponseDTO.java
  src/main/java/DC_square/spring/web/dto/response/place/PlaceDetailResponseDTO.java
  src/main/java/DC_square/spring/web/dto/response/place/PlaceResponseDTO.java
Labels: :bug:, :sparkle:

#86 DTO 수정
  src/main/java/DC_square/spring/service/MyReviewService.java
  src/main/java/DC_square/spring/web/dto/response/ReviewResponseDTO.java
Labels: :bug:

#87 버그 수정
  src/main/java/DC_square/spring/domain/entity/place/PlaceDetail.java
Labels: :bug:

#89 산책로 리뷰 삭제 버그 수정
  src/main/java/DC_square/spring/service/WalkService/WalkReviewService.java
  src/main/java/DC_square/spring/web/controller/walk/WalkReviewController.java
  src/main/java/DC_square/spring/web/controller/walk/WalkWishController.java
Labels: :bug:

#92 마이게시판 구현, 홈화면 게시판 연동
  src/main/java/DC_square/spring/domain/entity/community/MyBoard.java
  src/main/java/DC_square/spring/repository/community/BoardRepository.java
  src/main/java/DC_square/spring/repository/community/MyBoardRepository.java
  src/main/java/DC_square/spring/service/community/MyBoardService.java
  src/main/java/DC_square/spring/web/controller/community/MyBoardController.java
  src/main/java/DC_square/spring/web/dto/response/community/MyBoardResponseDto.java
Labels: :sparkle:

#93 Feat/minco/refresh token
  src/main/java/DC_square/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/DC_square/spring/apiPayload/exception/ExceptionAdvice.java
  src/main/java/DC_square/spring/apiPayload/exception/TokenException.java
  src/main/java/DC_square/spring/config/jwt/JwtAuthenticationFilter.java
  src/main/java/DC_square/spring/config/jwt/JwtTokenProvider.java
  src/main/java/DC_square/spring/config/jwt/RefreshTokenRedisRepository.java
  src/main/java/DC_square/spring/service/UserService.java
  src/main/java/DC_square/spring/service/WeatherService.java
  src/main/java/DC_square/spring/web/controller/TokenController.java
  src/main/java/DC_square/spring/web/dto/response/TokenDto.java
  src/main/java/DC_square/spring/web/dto/response/UserResponseDto.java
  src/main/java/DC_square/spring/web/dto/response/WeatherResponseDto.java
  src/main/java/DC_square/spring/web/dto/response/user/LoginResponseDto.java
Labels: :sparkle:

#94 검색 기능 분리, 검색 로직 변경
  src/main/java/DC_square/spring/service/place/GooglePlacesService.java
  src/main/java/DC_square/spring/service/place/PlaceService.java
  src/main/java/DC_square/spring/web/controller/place/PlaceController.java
  src/main/java/DC_square/spring/web/dto/response/place/PlacePageResponseDTO.java
Labels: :bug:

#96 핫플레이스 정렬방식 변경
  src/main/java/DC_square/spring/domain/entity/place/PlaceView.java
  src/main/java/DC_square/spring/repository/place/PlaceViewRepository.java
  src/main/java/DC_square/spring/service/place/PlaceService.java
  src/main/java/DC_square/spring/web/controller/place/PlaceController.java
  src/main/java/DC_square/spring/web/dto/response/place/HotPlaceResponseDTO.java
Labels: :bug:

#100 검색 버그 수정
  src/main/java/DC_square/spring/service/place/GooglePlacesService.java
  src/main/java/DC_square/spring/service/place/PlaceService.java
  src/main/java/DC_square/spring/web/controller/place/PlaceController.java
Labels: :bug:

#101 Feat/minco/user delete
  src/main/java/DC_square/spring/config/jwt/JwtTokenProvider.java
  src/main/java/DC_square/spring/service/UserService.java
  src/main/java/DC_square/spring/web/controller/UserController.java
Labels: :sparkle:

#102 데모데이 데이터를 삽입하기 위한 api 구현
  src/main/java/DC_square/spring/service/place/PlaceService.java
  src/main/java/DC_square/spring/web/controller/place/PlaceController.java
Labels: :sparkle:

#103 게시판 키워드 수정
  src/main/java/DC_square/spring/web/controller/community/BoardController.java
Labels: :sparkle:

#104 토큰 유효시간 정상화
  src/main/java/DC_square/spring/config/jwt/JwtTokenProvider.java
Labels: :sparkle:

#105 히든 속성 추가, 키워드 버그 수정
  src/main/java/DC_square/spring/domain/entity/place/Place.java
  src/main/java/DC_square/spring/service/place/PlaceService.java
Labels: :bug:, :sparkle:

#107 장소 리뷰 신고기능 구현
  src/main/java/DC_square/spring/domain/entity/place/Place.java
  src/main/java/DC_square/spring/domain/entity/place/ReviewReport.java
  src/main/java/DC_square/spring/domain/enums/ReportType.java
  src/main/java/DC_square/spring/repository/place/ReviewReportRepository.java
  src/main/java/DC_square/spring/service/place/PlaceReviewReportService.java
  src/main/java/DC_square/spring/service/place/PlaceReviewService.java
  src/main/java/DC_square/spring/web/controller/place/PlaceReviewController.java
  src/main/java/DC_square/spring/web/controller/place/PlaceReviewReportController.java
  src/main/java/DC_square/spring/web/dto/request/place/ReviewReportRequestDTO.java
  src/main/java/DC_square/spring/web/dto/response/place/ReviewReportResponseDTO.java
Labels: :sparkle:

#110 🐛 : 연관데이터 삭제로직 추가
  src/main/java/DC_square/spring/repository/community/PostLikeRepository.java
  src/main/java/DC_square/spring/service/UserService.java
Labels: :bug:, :sparkle:

#111 24시간, 주차가능, 영업중 필터기능 구현
  src/main/java/DC_square/spring/domain/entity/place/Place.java
  src/main/java/DC_square/spring/service/place/PlaceService.java
  src/main/java/DC_square/spring/web/controller/place/PlaceController.java
  src/main/java/DC_square/spring/web/controller/place/PlaceReviewReportController.java
  src/main/java/DC_square/spring/web/dto/request/place/FilteredPlaceRequestDTO.java
Labels: :sparkle:

#113 모든 게시글 조회
  src/main/java/DC_square/spring/service/community/PostService.java
  src/main/java/DC_square/spring/web/controller/community/PostController.java
Labels: :sparkle:

#114 반려동물 타입 반환 추가
  src/main/java/DC_square/spring/service/community/PostService.java
  src/main/java/DC_square/spring/web/dto/response/community/PostResponseDto.java
Labels: :sparkle:

#115 댓글 삭제에 userId 추가
  src/main/java/DC_square/spring/service/community/CommentService.java
  src/main/java/DC_square/spring/web/controller/community/CommentController.java
Labels: :sparkle:

#119 Feat/minco/home dday
  src/main/java/DC_square/spring/domain/entity/walk/Walk.java
  src/main/java/DC_square/spring/repository/WalkRepository/WalkRepository.java
  src/main/java/DC_square/spring/repository/WalkRepository/WalkReviewLikeRepository.java
  src/main/java/DC_square/spring/service/UserService.java
  src/main/java/DC_square/spring/service/dday/DdayService.java
  src/main/java/DC_square/spring/web/controller/HomeController.java
Labels: :sparkle:
